### ISSUE TITLE
在线演示的demo切换不了主题

### ISSUE THREAD

**Issue by martian98** [GitOfZGT/dynamic-theme-demos#2]
大佬你好, 访问这个地址: [https://gitofzgt.github.io/dynamic-theme-demos/vite-antd-vue-preset-theme/](url)
然后切换主题不生效.
![image](https://user-images.githubusercontent.com/66452310/157382348-b345e83f-6636-41ef-ac6a-8ead480247ab.png)

**Comment by GitOfZGT** [comment]
之前处理过，现在关掉issue
