### ISSUE TITLE
vite-antd-vue-preset-theme 好像不可以动态切换

### ISSUE THREAD

**Issue by StevenTang1994** [GitOfZGT/dynamic-theme-demos#3]
https://gitofzgt.github.io/dynamic-theme-demos/vite-antd-vue-preset-theme/ 

好像不能动态切换

**Comment by GitOfZGT** [comment]
> https://gitofzgt.github.io/dynamic-theme-demos/vite-antd-vue-preset-theme/
> 
> 好像不能动态切换

预设模式和动态模式 分开的，目前还无法共存。

动态切换demo： https://gitofzgt.github.io/vite-dynamictheme-antd-vue-demo/

**Comment by BeginnerDone** [comment]
[这个](https://gitofzgt.github.io/dynamic-theme-demos/vite-antd-vue-preset-theme/)  没有效果

**Comment by StevenTang1994** [comment]
没事了 已经弄好了 thank
